name: ThorKlein
favicon: null
layout_spectrum: 0.04773061606101692
typography_spectrum: 0.36622513830661774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070304'
    - '#9f191a'
    - '#beaea1'
    - '#966a47'
  brandStrength: 0.1875
  lightness: 0.41521579562686384
  saturation: 0.29494502348825336
  rhythmicContrast: 0.5020217094570398
purpose: []
