name: ThorKlein
favicon: null
layout_spectrum: 0.04773061606101692
typography_spectrum: 0.36622513830661774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7857782174833119
  lightness: 0.41521579562686384
  saturation: 0.29494502348825336
  rhythmicContrast: 0.5020217094570398
purpose: []
