name: ThorKlein
favicon: null
layout_spectrum: 0.12042
typography_spectrum: 0.36622513830661774
title: 'writer & director'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070304'
    - '#9f191a'
    - '#beaea1'
    - '#966a47'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
